### PR TITLE
allow for alpha value

### LINKED ISSUE #13: bg-opacity-* not working with radix colors
Hey, me again!

```
bg-slate-1 bg-opacity-10
```
or
```
bg-slate-1/50
```

won't work because tw uses css variables to set bg opacity. Honestly no idea how this could be solved though, I think both this and #12 are strictly related to referring to css variables instead of having straight-up strings.

### PR DESCRIPTION
**Pull request by Gravy59**
Simple lines of code and it all just works:tm:
Closes #13

### CODE REVIEW

**Comment by Gravy59** [comment]
Please squash these commits!

**Comment by devnomic** [comment]
Works great, please merge

**Comment by brattonross** [comment]
Thanks for the contribution. I've been meaning to get around to implementing this for a while.
I went ahead and fixed a couple of issues that I could see, but otherwise looks good!

Just a word of advice as well, maybe don't use curse words in your commits when contributing to other peoples' repositories. I personally am not bothered by it, and these commits are going to be squashed anyway, but others might take offense!

**Comment by Gravy59** [comment]
> maybe don't use curse words in your commits 

oh whoops! sorry! I was cursing my previous code I had written that _really stupidly_ had a regex that didn't allow for floating point values.
Thanks for merging!

**Pull request merged**
